# architecture
network:
  name: vgg # vgg or resnet
  output_layer: block5_conv2 # block5_conv2 for vgg or bn5c_branch2a/add_16 for resnet
  n_clusters: 64
  middle_pca:
    active: true
    dim: 128
    pretrain: true

# training
description: ""
mining_batch_size: 2048
minibatch_size: 6
steps_per_epoch: 400
n_epochs: 160
lr:
  warm-up: true
  warm-up-steps: 2000 # if warm-up is active
  max_value: 1e-5
resolution: 336 # not effective yet

# testing
rotate_holidays: true
use_power_norm: true
use_multi_resolution: false